# Generated by Django 2.0.dev20170906232138 on 2017-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
